//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmokiIDzikieWeze.UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressesRepositoryDB
    {
        public int AddressId { get; set; }
        public string Street { get; set; }
        public string HomeNumber { get; set; }
        public Nullable<int> ApartmentNumber { get; set; }
        public int PostalCode { get; set; }
        public string City { get; set; }
        public int CustomersRepositoryDBCustomerId { get; set; }
    
        public virtual CustomersRepositoryDB CustomersRepositoryDB { get; set; }
    }
}
